[project]
name = "jobby"
version = "0.0.1"
dependencies = [
    "requests",
    "pydantic",
    "networkx",
    "matplotlib",
    "pydot",
    'loguru',
    'dbt-core==1.3.0rc1'
]

[tool.setuptools.packages.find]
where = ["jobby"]

[project.optional-dependencies]
dev = ["pytest", "black"]
